"""added new column started

Revision ID: 67ccbc78fe87
Revises: b1bc0238f03a
Create Date: 2025-10-20 12:52:28.726244

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67ccbc78fe87'
down_revision: Union[str, Sequence[str], None] = 'b1bc0238f03a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('started', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'started')
    # ### end Alembic commands ###
